### ISSUE TITLE
怎么是使用的呢

### ISSUE THREAD

**Issue by qwhou** [yanghaiji/DataGrip#17]
如何配置才能正确的使用呢，需要那些环境？

**Comment by yanghaiji** [comment]
> 如何配置才能正确的使用呢，需要那些环境？

可以参考 https://github.com/yanghaiji/DataGrip/blob/main/README_zh.md
主要流程
### pg
1. 修改data-grip-exec项目里数据库连接配置
2. 启动data-grip-exec项目，访问http://localhost:8080/datagrip/api/gen/pg进行结构迁移
3. 启动data-grip-jdbc-cdc项目（需修改数据库连接配置），访问http://localhost:8081/jdbc/cdc/pg/sync进行数据迁移

### oracle to pg
1. 启动data-grip-jdbc-cdc项目（需修改数据库连接配置），访问http://localhost:8081/jdbc/cdc/ora/pg/sync即可

可以在 data-grip-jdbc-cdc 项目里 application-datagrip.yml 修改同步的频率和同步的表
